[package]
name = "rust-fetch"
version = "0.6.11"
authors = ["rumblefrog <contact@zhenyangli.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
bytes = "1"
env_logger = "0.9"
futures-retry = "0.6"
static_vcruntime = "1"

[dependencies.tokio]
version = "1"
features = ["rt-multi-thread"]

[dependencies.reqwest]
# version = "0.11"
git = "https://github.com/TextsHQ/reqwest"
branch = "fingerprint"
default-features = false
features = ["rustls-tls-native-roots", "gzip", "brotli"]

[dependencies.neon]
git = "https://github.com/neon-bindings/neon"
branch = "main"
default-features = false
features = ["napi-6", "event-queue-api", "try-catch-api"]

[profile.release]
lto = "fat"
codegen-units = 1
