name: Build
on:
  push:
    tags:
    - '*'

env:
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  MACOSX_DEPLOYMENT_TARGET: 10.11

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        node-version: [ 18.x ]
        include:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          architecture: x64
        - os: windows-latest
          target: x86_64-pc-windows-msvc
          architecture: x64
        - os: macos-latest
          target: x86_64-apple-darwin
          architecture: x64
        - os: macos-latest
          target: aarch64-apple-darwin
          architecture: arm64

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Configure git for private repos
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

    - name: Cache cargo bin
      uses: actions/cache@v2
      with:
        path: ~/.cargo/bin
        key: cargo-bin-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v2
      with:
        path: target
        key: cargo-build-target-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

    - name: Install latest Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn --ignore-scripts

    - name: Build
      run: yarn build --target=${{ matrix.target }}

      # Until GH action adds M1 runners, can't run aarch64 libs
    - name: Test
      if: ${{ matrix.architecture == 'x64' }}
      run: yarn test

    - name: Publish
      run: |
        yarn package --target_arch=${{ matrix.architecture }}
        yarn upload-binary
